import React, { useEffect, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { io } from 'socket.io-client'
import './styles.css'

const socket = io(import.meta.env.VITE_SOCKET_URL || 'http://localhost:3001')
const palette = ['#24233a','#ffffff','#ff5c70','#ffb020','#f7de40','#48d597','#42b4ff','#7c5cff','#eb70bf','#925e3c']
const settingsDefault = { maxPlayers: 8, rounds: 3, drawTime: 80, wordCount: 3, hints: true, private: true }

function App() {
  const [view, setView] = useState('home'); const [name, setName] = useState(''); const [roomCode, setRoomCode] = useState(''); const [room, setRoom] = useState(null); const [playerId, setPlayerId] = useState(''); const [settings, setSettings] = useState(settingsDefault); const [options, setOptions] = useState([]); const [timer, setTimer] = useState(0); const [messages, setMessages] = useState([]); const [error, setError] = useState('')
  useEffect(() => {
    socket.on('room:joined', ({ room: joinedRoom, playerId: joinedPlayerId }) => {
      setRoom(joinedRoom)
      setPlayerId(joinedPlayerId)
      setView('room')
    })
    socket.on('room:update', setRoom)
    socket.on('word:options', setOptions)
    socket.on('timer', setTimer)
    socket.on('error:message', setError)
    socket.on('chat:message', item => setMessages(items => [...items.slice(-24), item]))
    socket.on('round:end', ({ word }) => setMessages(items => [...items, { name: 'Round complete', text: `The word was ${word}`, correct: true }]))
    socket.on('game:over', () => setView('result'))
    return () => socket.removeAllListeners()
  }, [])
  const create = () => { if (!name.trim()) return setError('Enter a display name first.'); socket.emit('room:create', { name, settings }) }
  const join = () => { if (!name.trim() || !roomCode.trim()) return setError('Enter your name and a room code.'); socket.emit('room:join', { name, id: roomCode }) }
  if (view === 'home') return <Home {...{ name, setName, roomCode, setRoomCode, settings, setSettings, create, join, error, setError }} />
  return <Game {...{ room, playerId, options, timer, messages, setMessages, setOptions, view, setView }} />
}

function Home(p) { const change = (key, value) => p.setSettings(s => ({ ...s, [key]: value })); return <main className="landing"><nav><div className="brand"><i>✦</i> doodle<span>dash</span></div><div className="tag">draw together · guess faster</div></nav><section className="hero"><div className="hero-copy"><p className="eyebrow">A SOCIAL DRAWING GAME</p><h1>Make a mark.<br/><em>Make them guess.</em></h1><p className="intro">A bright little room for big doodles, wild guesses, and friendly competition.</p><div className="mini-cards"><div>✎<b>Draw anything</b><small>Simple tools, zero fuss</small></div><div>⌁<b>Play together</b><small>Live with your crew</small></div></div></div><div className="join-card"><div className="card-doodle">✦</div><h2>Start a room</h2><p>Pick a name and invite your favorite people.</p><input value={p.name} onChange={e => p.setName(e.target.value)} placeholder="Your display name" maxLength="18"/><button className="primary" onClick={p.create}>Create private room <span>→</span></button><div className="divider"><span>or join with a code</span></div><div className="code-row"><input value={p.roomCode} onChange={e => p.setRoomCode(e.target.value.toUpperCase())} placeholder="ROOM CODE" maxLength="5"/><button onClick={p.join}>Join</button></div>{p.error && <p className="error">{p.error}</p>}<button className="settings-link" onClick={() => document.querySelector('.settings').classList.toggle('open')}>Room settings ⚙</button><div className="settings"><label>Players <select value={p.settings.maxPlayers} onChange={e => change('maxPlayers', +e.target.value)}>{[2,4,6,8,12,16].map(x => <option key={x}>{x}</option>)}</select></label><label>Rounds <select value={p.settings.rounds} onChange={e => change('rounds', +e.target.value)}>{[2,3,4,5].map(x => <option key={x}>{x}</option>)}</select></label><label>Draw time <select value={p.settings.drawTime} onChange={e => change('drawTime', +e.target.value)}>{[45,60,80,120].map(x => <option key={x} value={x}>{x}s</option>)}</select></label><label>Word choices <select value={p.settings.wordCount} onChange={e => change('wordCount', +e.target.value)}>{[1,2,3,4,5].map(x => <option key={x}>{x}</option>)}</select></label><label>Hints <select value={String(p.settings.hints)} onChange={e => change('hints', e.target.value === 'true')}><option value="true">On</option><option value="false">Off</option></select></label></div></div></section><footer>Built for quick sketches and even quicker laughs <span>✦</span> No account needed</footer></main> }

function Game({ room, playerId, options, timer, messages, setMessages, setOptions, view, setView }) {
  const me = room.players.find(p => p.id === playerId); const drawer = room.players[room.turn]; const isDrawer = drawer?.id === playerId
  if (view === 'result') { const winner = [...room.players].sort((a,b) => b.score-a.score)[0]; return <main className="result"><div className="trophy">★</div><p>GAME COMPLETE</p><h1>{winner?.name} wins!</h1><div className="final-list">{[...room.players].sort((a,b)=>b.score-a.score).map((p,i)=><div key={p.id}><span>#{i+1}</span><b>{p.name}</b><strong>{p.score} pts</strong></div>)}</div><button className="primary" onClick={() => location.reload()}>Play again</button></main> }
  if (room.phase === 'lobby') return <main className="lobby"><header className="game-header"><div className="brand"><i>✦</i> doodle<span>dash</span></div><div className="room-pill">PRIVATE ROOM <b>{room.id}</b></div></header><section className="lobby-card"><p className="eyebrow">YOUR ROOM IS READY</p><h1>Gather your <em>creative chaos.</em></h1><p>Share this code with friends to let them join.</p><div className="invite"><b>{room.id}</b><button onClick={() => navigator.clipboard.writeText(room.id)}>Copy code</button></div><div className="player-grid">{room.players.map((p,i)=><div className="player-card" key={p.id}><span style={{background:p.color}}>{['✎','☻','✦','☁'][i%4]}</span><b>{p.name}{p.id===playerId && ' (you)'}</b><small>{p.id===room.hostId ? 'HOST' : 'READY'}</small></div>)}{Array.from({length:Math.max(0, Math.min(4, room.settings.maxPlayers)-room.players.length)}).map((_,i)=><div className="player-card empty" key={i}>+<small>WAITING</small></div>)}</div>{playerId === room.hostId ? <button className="primary begin" disabled={room.players.length<2} onClick={() => socket.emit('game:start', {id:room.id})}>{room.players.length<2 ? 'Waiting for a player…' : 'Start the game →'}</button> : <p className="waiting">Waiting for {room.players.find(p=>p.id===room.hostId)?.name} to start the game…</p>}</section></main>
  return <main className="game"><header className="game-header"><div className="brand"><i>✦</i> doodle<span>dash</span></div><div className="round"><b>ROUND {room.round + 1} / {room.settings.rounds}</b><span>{room.phase === 'choosing' ? 'Choosing a word' : room.masked}</span></div><div className={'timer '+(timer<15?'hot':'')}>{room.phase==='playing' ? `${timer}s` : '…'}</div></header><div className="game-layout"><aside className="scoreboard"><h3>PLAYERS</h3>{[...room.players].sort((a,b)=>b.score-a.score).map((p,i)=><div className={'score '+(p.id===drawer?.id?'drawing':'')} key={p.id}><span className="avatar" style={{background:p.color}}>{['✎','☻','✦','☁'][i%4]}</span><div><b>{p.name}{p.id===playerId&&' (you)'}</b><small>{p.id===drawer?.id?'drawing now':`${p.score} points`}</small></div><strong>{p.score}</strong></div>)}</aside><section className="canvas-zone">{room.phase === 'choosing' && isDrawer ? <div className="chooser"><p>IT’S YOUR TURN</p><h2>Choose a word to draw</h2><div>{options.map(word=><button key={word} onClick={()=>{socket.emit('word:choose',{id:room.id,word});setOptions([])}}>{word}</button>)}</div></div> : room.phase === 'choosing' ? <div className="chooser"><p>GET READY</p><h2>{drawer?.name} is choosing a word…</h2><div className="dots">● ● ●</div></div> : <Canvas room={room} isDrawer={isDrawer} />}{room.phase === 'reveal' && <div className="reveal"><p>THE WORD WAS</p><h2>{room.word || 'revealing…'}</h2></div>}</section><Chat {...{ room, messages, setMessages, isDrawer, me }} /></div></main>
}

function Canvas({ room, isDrawer }) { const ref=useRef(null); const [color,setColor]=useState('#24233a'); const [size,setSize]=useState(7); const active=useRef(false); const last=useRef(null); const strokes=useRef(room.strokes||[]); const draw=(stroke,ctx)=>{ctx.strokeStyle=stroke.color;ctx.lineWidth=stroke.size;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(stroke.from.x,stroke.from.y);ctx.lineTo(stroke.to.x,stroke.to.y);ctx.stroke()}; const paint=()=>{const c=ref.current,ctx=c?.getContext('2d');if(!ctx)return;ctx.clearRect(0,0,c.width,c.height);strokes.current.forEach(s=>draw(s,ctx))}; useEffect(()=>{const c=ref.current;const resize=()=>{const box=c.getBoundingClientRect();c.width=box.width*devicePixelRatio;c.height=box.height*devicePixelRatio;c.getContext('2d').scale(devicePixelRatio,devicePixelRatio);paint()};resize();const stroke=s=>{strokes.current.push(s);paint()};socket.on('canvas:stroke',stroke);socket.on('canvas:replace',data=>{strokes.current=data;paint()});return()=>{socket.off('canvas:stroke',stroke);socket.off('canvas:replace');}},[]); const point=e=>{const b=ref.current.getBoundingClientRect();return{x:e.clientX-b.left,y:e.clientY-b.top}}; const start=e=>{if(!isDrawer)return;active.current=true;last.current=point(e)}; const move=e=>{if(!active.current||!isDrawer)return;const to=point(e),stroke={from:last.current,to,color,size};strokes.current.push(stroke);draw(stroke,ref.current.getContext('2d'));socket.emit('canvas:stroke',{id:room.id,stroke});last.current=to}; return <><canvas ref={ref} className={'drawing '+(!isDrawer?'locked':'')} onPointerDown={start} onPointerMove={move} onPointerUp={()=>active.current=false} onPointerLeave={()=>active.current=false}/>{isDrawer&&<div className="tools"><div className="colors">{palette.map(c=><button aria-label={c} key={c} style={{background:c}} className={color===c?'selected':''} onClick={()=>setColor(c)}/>)}</div><button onClick={()=>setSize(size===7?18:7)}>◉ Size</button><button onClick={()=>socket.emit('canvas:undo',{id:room.id})}>↶ Undo</button><button onClick={()=>socket.emit('canvas:clear',{id:room.id})}>Clear</button></div>}</> }

function Chat({room,messages,isDrawer,me}) { const [text,setText]=useState(''); const send=e=>{e.preventDefault();if(!text.trim())return;socket.emit('guess:send',{id:room.id,text});setText('')}; return <aside className="chat"><div className="chat-title">GUESSES <span>✦</span></div><div className="messages">{messages.length?messages.map((m,i)=><p className={m.correct?'correct':''} key={i}><b>{m.name}</b> {m.text}</p>):<p className="quiet">Be the first to guess it!</p>}</div><form onSubmit={send}><input disabled={isDrawer||room.phase!=='playing'} value={text} onChange={e=>setText(e.target.value)} placeholder={isDrawer?'You are drawing':'Type your guess…'}/><button>→</button></form></aside> }

createRoot(document.getElementById('root')).render(<App />)
